; Script generated by the HM NIS Edit Script Wizard.

;compiler direktiven
SetCompress force
SetCompressor /SOLID lzma
SetDatablockOptimize on
XPStyle on
;compiler direktiven

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "submatixBTLog"
!define PRODUCT_VERSION "1.2.6"
!define PRODUCT_PUBLISHER "Dirk Marciniak"
!define PRODUCT_WEB_SITE "http://www.submatix.com"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; Meine Variablen zur Vereinfachung
!define START_LINK "$SMPROGRAMS\submatixBTLog\submatixBTLog Ver. ${PRODUCT_VERSION}.lnk"
!define DEBUG_LINK "$SMPROGRAMS\submatixBTLog\submatixBTLog Ver. ${PRODUCT_VERSION} DEBUG.lnk"
!define SOURCE_FILES "C:\DATEN\Entwicklung\IntelliJ\SubmatixBTForPC\installFiles"
!define JAR_SOURCE "C:\DATEN\Entwicklung\IntelliJ\SubmatixBTForPC\jar"

!include "MUI2.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${SOURCE_FILES}\progicon.ico"
!define MUI_UNICON "${SOURCE_FILES}\unicon.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "license.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\submatix_start.cmd"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "SubmatixBTLog-${PRODUCT_VERSION}-Setup.exe"
InstallDir "$PROGRAMFILES\submatixBTLog"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MAIN" SEC01
  SetOutPath "$INSTDIR"
  CreateDirectory "$INSTDIR\lib"
  SetOverwrite ifnewer
  File "${JAR_SOURCE}\SubmatixBTConfigPC.jar"
  File "${SOURCE_FILES}\submatix_start_this_on_trouble.cmd"
  File "${SOURCE_FILES}\submatix_start.cmd"
  File "${SOURCE_FILES}\progicon.ico"
  File "${SOURCE_FILES}\unicon.ico"
  CreateDirectory "$SMPROGRAMS\submatixBTLog"
  CreateShortCut "${START_LINK}" "$INSTDIR\submatix_start.cmd" icon.file "$INSTDIR\progicon.ico"
  CreateShortCut "${DEBUG_LINK}" "$INSTDIR\submatix_start_this_on_trouble.cmd" icon_file "$INSTDIR\progicon.ico"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  CreateDirectory "$SMPROGRAMS\submatixBTLog"
  CreateShortCut "$SMPROGRAMS\submatixBTLog\Uninstall.lnk" "$INSTDIR\uninst.exe" icon_file "$INSTDIR\unicon.ico"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) wurde erfolgreich deinstalliert."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "M�chten Sie $(^Name) und alle seine Komponenten deinstallieren?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\submatix_start.cmd"
  Delete "$INSTDIR\submatix_start_this_on_trouble.cmd"
  Delete "$INSTDIR\submatixBTForPC.jar"
  Delete "$INSTDIR\versioncheck.jar"
  Delete "$INSTDIR\unicon.ico"
  Delete "$INSTDIR\progicon.ico"
  Delete "$INSTDIR\derby.log"
  Delete "$INSTDIR\spxLogProgram.conf"
  Delete "$SMPROGRAMS\submatixBTLog\Uninstall.lnk"
  Delete "${START_LINK}"
  Delete "${DEBUG_LINK}"
  RMDir /r /REBOOTOK "$SMPROGRAMS\submatixBTLog"
  RMDir "$INSTDIR\lib"
  RMDir /r /REBOOTOK  "$INSTDIR"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd